version: '2'

services:
  web:
    image: nginx:stable
    ports:
      - "80:80"
      - "9001:9001"
    volumes:
        - ../:/var/www
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    volumes:
      - ../:/var/www

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
