version: '2'

services:
  web:
    image: nginx:stable
    ports:
      - "81:80"
      - "9002:9001"
    volumes:
        - ../:/var/www
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    volumes:
      - ../:/var/www

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=remembender
      - MYSQL_USER=remembender
      - MYSQL_PASSWORD=remembender
